const fs = require('fs');
const path = require('path');
const { withXcodeProject } = require('expo/config-plugins');

const SWIFT_SOURCE = `import DeviceCheck
import React

@objc(WingrDeviceCheck)
class WingrDeviceCheck: NSObject {
  @objc
  static func requiresMainQueueSetup() -> Bool {
    false
  }

  @objc
  func generateToken(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    guard DCDevice.current.isSupported else {
      reject(
        "ERR_DEVICECHECK_UNSUPPORTED",
        "DeviceCheck is unavailable on this device.",
        nil
      )
      return
    }

    DCDevice.current.generateToken { token, error in
      if let error {
        reject("ERR_DEVICECHECK_TOKEN", "Could not verify this device.", error)
        return
      }
      guard let token else {
        reject("ERR_DEVICECHECK_TOKEN", "Could not verify this device.", nil)
        return
      }
      resolve(token.base64EncodedString())
    }
  }
}
`;

const OBJECTIVE_C_SOURCE = `#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(WingrDeviceCheck, NSObject)

RCT_EXTERN_METHOD(
  generateToken:(RCTPromiseResolveBlock)resolve
  rejecter:(RCTPromiseRejectBlock)reject
)

@end
`;

function withWingrDeviceCheck(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const target = project.getFirstTarget();
    const projectName = config.modRequest.projectName;
    const sourceDirectory = path.join(
      config.modRequest.platformProjectRoot,
      projectName,
    );
    const group = project.findPBXGroupKey({ name: projectName });
    if (!group) {
      throw new Error('Could not find the iOS app group for WingrDeviceCheck.');
    }

    for (const [filename, source] of [
      ['WingrDeviceCheck.swift', SWIFT_SOURCE],
      ['WingrDeviceCheck.m', OBJECTIVE_C_SOURCE],
    ]) {
      fs.writeFileSync(path.join(sourceDirectory, filename), source);

      // The app group has no path, so Xcode resolves a bare filename from
      // ios/. Always register the project-relative path instead.
      const filePath = path.posix.join(projectName, filename);

      // Repair projects generated by the previous plugin version, which
      // registered the bare filename and therefore pointed at ios/<file>.
      if (project.hasFile(filename)) {
        project.removeSourceFile(filename, { target: target.uuid }, group);
      }

      if (!project.hasFile(filePath)) {
        project.addSourceFile(filePath, { target: target.uuid }, group);
      }
    }

    return config;
  });
}

module.exports = withWingrDeviceCheck;
